# point_name:
# - x
# - y
# - theta

world:
- 0
- 0
- 0
home_entry:
- 1.56
- 0
- 1.57
center:
- 1.56
- 2.7
- 1.57
bridge:
- 1.56
- 4.3
- 1.57
quad_a:
- 3.7
- 2.7
- 0
quad_b:
- 1.8
- 4.3
- 0
double_a:
- 0
- 2.4
- 3.14
double_b:
- 1
- 4
- 3.14
double_c:
- 0.6
- 5
- 3.14
port:
- 1.56
- 7.4
- 0
sextuple:
- 0
- 7.6
- 1.57
racks_entry:
- 3.5
- 7.8
- 0
racks_drink:
- 3.8
- 6.8
- 0
racks_meal:
- 3.8
- 10
- 0

# parent/child
relations:
- world/home_entry
- home_entry/center
- center/quad_a
- center/double_a
- center/bridge
- bridge/double_b
- bridge/double_c
- bridge/quad_b
- bridge/port
- port/sextuple
- port/racks_entry
- racks_entry/racks_drink
- racks_entry/racks_meal
