controller_manager:
  ros__parameters:
    update_rate: 100

    JSB:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    JTC:
      type: joint_trajectory_controller/JointTrajectoryController

JSB:
  ros__parameters:
    joints:
      - y_front_omni_joint
      - y_rear_omni_joint
      - x_right_omni_joint
      - x_left_omni_joint
      - front_left_mecanum_joint
      - front_right_mecanum_joint
      - rear_left_mecanum_joint
      - rear_right_mecanum_joint

    interfaces:
      - position

JTC:
  ros__parameters:
    joints:
      - front_left_mecanum_joint
      - front_right_mecanum_joint
      - rear_left_mecanum_joint
      - rear_right_mecanum_joint
    
    command_interfaces:
      - velocity
    
    state_interfaces:
      - position
      - velocity


    